version: '3'
services:
        achievement-server:
                build: ./frontend/
                ports:
                        - "80:3000"
                restart: always
        redis:
                image: redis
                volumes:
                        - data:/data
volumes:
        data: {}
