version: '3'
services:
        achievement-server:
                build: 
                        context: ../
                        dockerfile: ./server/frontend/Dockerfile
                ports:
                        - "80:3000"
                restart: always
                environment:
                        - NODE_ENV=production
                        - REDIS_URL=redis
                        - DB_URL=postgres
                links:
                        - redis
                        - postgres
        achievement-processing:
                build:
                        context: ../
                        dockerfile: ./server/processing-server/Dockerfile

                restart: always
                environment:
                        - NODE_ENV=production
                        - REDIS_URL=redis
                        - DB_URL=postgres
                links:
                        - redis
                        - postgres
        redis:
                image: redis
                restart: always
                volumes:
                        - redis-volume:/data
                expose:
                        - "6379"
        postgres:
                image: postgres
                restart: always
                volumes:
                        - postgresql-volume:/var/lib/postgresql/data
                        - ./db-server/structure.sql:/docker-entrypoint-initdb.d/structure.sql
                expose:
                        - "5432"
                environment: # TODO: Use docker secrets for production...
                        POSTGRES_PASSWORD: dev
                        POSTGRES_USER: dev
                        POSTGRES_DB: achievements
volumes:
        redis-volume: {}
        postgresql-volume: {}