version: '3'
services:
        redis:
                image: redis:alpine
                ports: # ONLY FOR DEV
                        - 6379:6379
                volumes:
                        - redis-volume:/data
        postgres:
                image: postgres
                ports: # ONLY FOR DEV
                        - 5432:5432
                volumes:
                        - postgresql-volume:/var/lib/postgresql/data
                        - ./db-server/structure.sql:/docker-entrypoint-initdb.d/structure.sql
                environment:
                        POSTGRES_PASSWORD: dev
                        POSTGRES_USER: dev
                        POSTGRES_DB: achievements
                        PGDATA: /tmp
volumes:
        redis-volume: {}
        postgresql-volume: {}
